{% set name = "ipyelk" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyelk-{{ version }}.tar.gz
  sha256: e0ac540c02526efc1c422f925ddbc0a6e45b08eb36830ce415e9a8b63aac9303

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipywidgets >=7.5.0
    - networkx
    - python >=3.7

test:
  imports:
    - ipyelk
    - ipyelk.diagram
    - ipyelk.nx
    - ipyelk.schema
    - ipyelk.tools
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyelk
  summary: ELK widget for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - COPYRIGHT.md
    - third-party/epl-v10.html

extra:
  recipe-maintainers:
    - bollwyvl
