{% set name = "ipyelk" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyelk-{{ version }}.tar.gz
  sha256: afe4f896a8513a0d812f35b3cb083b21ac40d496b7c471a4a66d5dcaa7998cbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - async-lru >=1,<2
    - ipywidgets >=7.5.0
    - networkx
    - python >=3.7

test:
  imports:
    - ipyelk
    - ipyelk.diagram
    - ipyelk.nx
    - ipyelk.schema
    - ipyelk.tools
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyelk
  summary: ELK widget for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - COPYRIGHT.md
    - third-party/epl-v10.html

extra:
  recipe-maintainers:
    - bollwyvl
